/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Range {
    public static int[] endPoints(String r) {
        char[] x = new char[r.length()];

        for(int i = 0; i < r.length(); i++)
        {
            x[i] = r.charAt(i);
        }
        int[] rangeEndpoint;

        int size = x.length;
        int startPoint = 0;
        int endPoint = 0;

        char openBracket = x[0], closeBracket = x[size - 1];

        int leftExtremeValue = Character.getNumericValue(x[1]);
        int rightExtremeValue = Character.getNumericValue(x[size - 2]);

        if(openBracket == '(' && closeBracket == ')'){
            startPoint = leftExtremeValue + 1;
            endPoint = rightExtremeValue -1;
        }
        if(openBracket == '[' && closeBracket == ')'){
            startPoint = leftExtremeValue;
            endPoint = rightExtremeValue -1;
        }
        if(openBracket == '(' && closeBracket == ']'){
            startPoint = leftExtremeValue + 1;
            endPoint = rightExtremeValue;
        }
        if(openBracket == '[' && closeBracket == ']'){
            startPoint = leftExtremeValue;
            endPoint = rightExtremeValue;
        }

        rangeEndpoint = new int[2];
        rangeEndpoint[0] = startPoint;
        rangeEndpoint[1] = endPoint;
        return rangeEndpoint;


    }
}
