/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class RangeTest {

    @Test public void testEndpointTC1() {
        int[] expected  = {2,4};
        int[] recieved = Range.endPoints("[2,5)");
        boolean pass = false;
        if (expected[0] == recieved[0] && expected[1] == recieved[1]){
            pass = true;
        }
        assertTrue("test", pass);
    }
}
